export const MessageTypes = {
  INIT: 'init',
  JOIN: 'join',
  LEAVE: 'leave',
  INPUT: 'input',
  GAME_STATE: 'gameState',
  PLAYER_JOINED: 'playerJoined',
  PLAYER_LEFT: 'playerLeft',
  FIRE: 'fire',
  HIT: 'hit',
  PROJECTILE_SPAWN: 'projectileSpawn',
  PROJECTILE_REMOVE: 'projectileRemove',
  ENTER_VEHICLE: 'enterVehicle',
  EXIT_VEHICLE: 'exitVehicle',
  VEHICLE_UPDATE: 'vehicleUpdate',
  GRAB_GHOST: 'grabGhost',
  DROP_GHOST: 'dropGhost',
  THROW_GHOST: 'throwGhost',
  GHOST_UPDATE: 'ghostUpdate'
};